[project]
name = "category-tree"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.9",
    "django-extensions>=4.1",
    "django-ninja>=1.5.0",
    "django-stubs>=5.2.8",
    "mypy>=1.19.0",
    "pillow>=12.0.0",
]

[tool.mypy]
python_version = "3.12"
plugins = ["mypy_django_plugin.main"]
mypy_path = ["src"]
explicit_package_bases = true

ignore_missing_imports = true
warn_unused_ignores = true
warn_return_any = true
disallow_untyped_defs = false
strict_optional = true

[tool.django-stubs]
django_settings_module = "category_tree.settings"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
]
