# Generated by Django 5.2.9 on 2025-12-02 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="img/categories/"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="api.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategorySimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_category1",
                        to="api.category",
                    ),
                ),
                (
                    "category2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_category2",
                        to="api.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="similar_categories",
            field=models.ManyToManyField(
                related_name="similar_to",
                through="api.CategorySimilarity",
                to="api.category",
            ),
        ),
        migrations.AddIndex(
            model_name="categorysimilarity",
            index=models.Index(
                fields=["category1"], name="api_categor_categor_bdde87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categorysimilarity",
            index=models.Index(
                fields=["category2"], name="api_categor_categor_6ba9b6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="categorysimilarity",
            constraint=models.CheckConstraint(
                condition=models.Q(("category1", models.F("category2")), _negated=True),
                name="no_self_similarity",
            ),
        ),
        migrations.AddConstraint(
            model_name="categorysimilarity",
            constraint=models.CheckConstraint(
                condition=models.Q(("category1__lt", models.F("category2"))),
                name="category1_lt_category2",
            ),
        ),
        migrations.AddConstraint(
            model_name="categorysimilarity",
            constraint=models.UniqueConstraint(
                fields=("category1", "category2"), name="unique_similarity_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent"], name="api_categor_parent__d9272b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="api_categor_name_53a3ad_idx"),
        ),
    ]
