# Generated by Django 5.2.9 on 2025-12-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="categorysimilarity",
            options={"verbose_name_plural": "Category similarities"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="path",
        ),
    ]
